### ISSUE TITLE
Cannot access dashboard on v0.9.9-rc.2

### ISSUE THREAD

**Issue by cknowles** [kubernetes-retired/kube-aws#1001] opened 2017-11-07 07:01 UTC
I updated a dev cluster using v0.9.9-rc.2 but I can not longer access the dashboard on the existing domain that goes via the ELB setup by kube-aws.

I get this when I load the page:
```
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.2.7.5:8443/'
```

It seems related to https://github.com/kubernetes-incubator/kube-aws/pull/971. This PR changed the service target port to 8443 but left the container port as 9090 so I'm a bit unsure if anyone has this working.

**Comment by mumoshu** [comment] 2017-11-07 07:09
Would this work for you?
https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#api-server

**Comment by mumoshu** [comment] 2017-11-07 07:14
Anyway, the change in the port does seem suspicious!

**Comment by c-knowles** [comment] 2017-11-07 07:16
I can't currently attempt it as the cluster is not in a workable state for some seemingly unrelated reason. What I would say is accessing the dashboard always worked fine via `https://EXTERNAL_DNS/ui` prior to these changes (which then prompted to supply the client SSL cert). I don't mind changing access pattern but it's not documented right now and doesn't seem to work out of the box.

The port on the service does not seem to map to any exposed port on the deployment anymore which it why I wondered if this works for anyone.

**Comment by mumoshu** [comment] 2017-11-07 07:48
@c-knowles Thanks for clarification!

Two things:

- the access pattern of kubernetes-dashboard has changed since v1.7.x and therefore `https://EXTERNAL_DNS/ui` won't work regardless of the port setting is valid or not.
   - Probably we may want to add link to https://github.com/kubernetes/dashboard/wiki/Accessing-dashboard somewhere in the kube-aws doc so that an user can consult the dashboard doc whenever the kube-aws doc gets outdated about the access pattern of kubernetes-dashboard.
- Your concern seems valid to me - I'll try it myself while running tests towards next kube-aws release.

**Comment by c-knowles** [comment] 2017-11-07 07:52
As far as I understand it, the `/ui` is not available but the [access pattern](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#api-server) used before should still work.

**Comment by camilb** [comment] 2017-11-07 09:58
@c-knowles @mumoshu  I have used the [recommended](https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml) setup, which it's still not very easy to expose because of the self generated certificates but works fine locally using `kubectl port-forward kubernetes-dashboard-xxxxx 8443:8443 -n kube-system`. If we disable the certificates, we can not use the authentication anymore, so it will behave as the old version. 

I'm using a modified version that mounts another secret with trusted certificates named in the same way as those generated by the init container and expose it externally using a LB with roles for different developer teams.

We have a flag in `cluster.yaml` `kubeDashboardAdminPrivileges` set to `true`  by default that disables the authentication and enables admin privileges. In this case we can also disable the fallowing args, which will not generate the certificates: 

          - --tls-key-file=/certs/dashboard.key
          - --tls-cert-file=/certs/dashboard.crt

Also we can set the port as 9090, since 8443 is used for TLS. 

I can create a PR with these changes today, if you consider this is the way to go. 
I prefer having authentication with RBAC permission so I can share it with multiple teams. Personally I don't use the dashboard at all, but is very fast and useful for developers and I consider that should be restricted when is exposed externally, both by authentication and RBAC permissions. Locally still works as expected.

**Comment by camilb** [comment] 2017-11-07 10:08
Exposing the dashboard using a LB example:

    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "kubedash.example.com"
      name: kubernetes-dashboard
      labels:
        run: kubernetes-dashboard
      namespace: kube-system
    spec:
      type: LoadBalancer
      loadBalancerSourceRanges:
      - x.x.x.x/32
      ports:
      - port: 443
        targetPort: 8443
        protocol: TCP
      selector:
        k8s-app: kubernetes-dashboard

**Comment by c-knowles** [comment] 2017-11-07 15:05
Strange, http://localhost:8001/ lists `/ui` on a fresh cluster but it redirects to a page which gives the same `malformed` response. Going to `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/` directly does seemingly work. Same behaviour via the API ELB on `https://DOMAIN/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`.

Not sure if there is some setting we can change to get the `/ui` redirect fixed. Any ideas?

Just have to figure out why the cluster upgrade is not working, likely credential problems again.

**Comment by c-knowles** [comment] 2017-11-07 15:16
Looks like the redirect is covered in https://github.com/kubernetes/kubernetes/issues/52729 but will be removed by https://github.com/kubernetes/kubernetes/pull/53766.

**Comment by c-knowles** [comment] 2017-11-08 02:15
@camilb @mumoshu what I did so far was also expose the container port 8443 as well as 9090 (matching the dockerfile) and then I managed to access the dashboard via the API ELB but using the longer direct link rather than `/ui` redirect.

**Comment by zhangtiny123** [comment] 2017-11-16 09:44
Hi , I also tried to access the dashboard.

I followed the guide https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above , and use ```kubectl proxy``` to start the local server.

Then open the link  http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/  ,choose kubeconfig file to authenticate, but failed with a message ```Not enough data to create auth info structure.```

Any suggestions please ?

**Comment by zhangtiny123** [comment] 2017-11-16 11:40
I'm sorry , got it from the wiki of kubernetes dashboard repo.

**Comment by c-knowles** [comment] 2017-11-16 15:26
I’m not sure why we removed port 8443 still as it’s needed as far as I can see to keep the existing use case of the dashboard being available via the API ELB. I’ve tweaked my setup locally for that as above, it works at first and I get the login page. However, then I get some odd behaviour after around a day that the same URL either does not respond at all or started prompting for the client SSL cert which was the old mechanism. I have yet to work out what is going on there but I haven’t really changed any of the auth settings compared with the last release.

**Comment by camilb** [comment] 2017-11-16 15:31
@zhangtiny123 Please use `kubectl port-forward kubernetes-dashboard-xxxxx 8443:8443 -n kube-system`

@c-knowles I'll create a new PR next week to fix these issues. I got it working well for more use cases.

**Comment by c-knowles** [comment] 2017-11-16 15:41
@camilb that’d be awesome, I’m also going to have a quick look tomorrow to see if I can fix up that case.

**Comment by camilb** [comment] 2017-11-22 15:40
@c-knowles The port was fixed in #1016.  To be able to keep the authentication and expose the dashboard using Ingress or LB with a trusted certificate, we need to wait for Dashboard version 1.8 which includes this PR https://github.com/kubernetes/dashboard/pull/2557.

**Comment by c-knowles** [comment] 2017-11-22 15:50
@camilb cool. I'm trying to understand the PR you linked and why we need it. Can you help me understand the current behaviour? It seems I get a mixture of client SSL prompts and login webpage but it's not stable and sometimes works fine but other times times out or otherwise errors out.

**Comment by camilb** [comment] 2017-11-22 16:10
In 1.8 we'll have 2 options: 

1. Current setup: generate self signed certificates with the init container and access the dashboard using  `kubectl proxy` on this URL:  

        http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/



 or externally using only a TCP ELB like this:

        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "kubedash.example.com"
          name: kubernetes-dashboard
          labels:
            run: kubernetes-dashboard
          namespace: kube-system
        spec:
          type: LoadBalancer
          loadBalancerSourceRanges:
          - x.x.x.x/32
          ports:
          - port: 443
            targetPort: 8443
            protocol: TCP
          selector:
            k8s-app: kubernetes-dashboard

_I can confirm that this works fine right now. Please let me know if you find any issues._

2. Allow exposing the dashboard externally using trusted certificates thru a Ingress or ELB by passing the `--enable-insecure-login` flag from https://github.com/kubernetes/dashboard/pull/2557, remove the self-signer certificates and keep the authentication.

**Comment by camilb** [comment] 2017-11-22 16:12
Right now, by default, the authentication is disabled by the `kubeDashboardAdminPrivileges` key in `cluster.yaml` and the Dashboard can be accessed fine using `kubectl proxy`.  Does anyone plan to expose the dashboard with admin privileges thru a Ingress or ELB and without authentication?

**Comment by c-knowles** [comment] 2017-11-22 16:35
Is 1)b) (TCP ELB) supposed to work with client SSL certs or webpage login or both?

**Comment by camilb** [comment] 2017-11-22 16:45
@c-knowles The init container in kubernetes-dashboard is generating the self-signed certificates and store them in a secret that is mounted as a volume in kubernetes-dashboard container. In this case you'll have only the webpage login: 
![screen shot 2017-11-22 at 17 36 47](https://user-images.githubusercontent.com/2655869/33139194-dca8c50e-cfac-11e7-89cc-915b57c37de5.png)

**Comment by camilb** [comment] 2017-11-22 16:46
In my case I have replaced the certificates in the secret with trusted certificates

**Comment by camilb** [comment] 2017-11-22 16:47
Another advantage of using authentication is that you can assign RBAC permissions to the generated tokens.

**Comment by c-knowles** [comment] 2017-11-23 07:21
@camilb so webpage login only? Using `kubeDashboardAdminPrivileges: false` from master seems to give me a mixture of webpage login and client SSL cert prompts. Not sure why I'm sometimes getting one and sometimes the other.

**Comment by camilb** [comment] 2017-11-27 18:57
@c-knowles I hope this PR #1040 covers most of the use cases. Please let me know if you have any suggestions on how we can improve it.

**Comment by c-knowles** [comment] 2017-11-28 16:30
We should include this in our release notes [from here](https://github.com/kubernetes/dashboard/wiki/Installation#recommended-setup). We need the same warning just for upgrading from old versions of kube-aws:

```
IMPORTANT: When upgrading from older version of Dashboard to 1.7+ make sure to delete 
Cluster Role Binding for kubernetes-dashboard Service Account, otherwise Dashboard will 
have full admin access to the cluster.
```

This command is enough:
`kubectl delete clusterrolebinding kubernetes-dashboard`

**Closed as completed** 2017-12-05 03:03 UTC
Labels: help wanted
